export const SPEC_LABELS: Record<string, string> = {
	weight: "Вес",
	compressive_strength: "Прочность на сжатие",
	setting_time: "Время схватывания",
	fineness: "Тонкость помола",
	moisture_content: "Влажность",
	dimensions: "Размеры",
	density: "Плотность",
	water_absorption: "Водопоглощение",
	diameter: "Диаметр",
	yield_strength: "Предел текучести",
	tensile_strength: "Предел прочности",
	weight_per_meter: "Вес на метр",
	grade: "Марка",
	power: "Мощность",
	no_load_speed: "Обороты без нагрузки",
	chuck_capacity: "Патрон",
	voltage: "Напряжение",
	thickness: "Толщина",
	adhesive_type: "Тип клея",
	volume: "Объем",
	coverage: "Расход",
	finish: "Финиш",
	drying_time: "Время высыхания",
	sheen: "Степень блеска",
	strength_class: "Класс прочности",
	consumption: "Расход",
	application_layer: "Слой нанесения",
	class: "Класс",
	slump: "Подвижность",
	max_aggregate: "Макс. фракция",
	frost_resistance: "Морозостойкость",
	strength: "Прочность",
	thermal_conductivity: "Теплопроводность",
	length: "Длина",
	size: "Размер",
	coating: "Покрытие",
	impact_energy: "Энергия удара",
	max_diameter: "Макс. диаметр",
	modes: "Режимы",
	range: "Дальность",
	accuracy: "Точность",
	battery: "Аккумулятор",
	protection: "Защита",
	mount: "Крепление",
	odor: "Запах",
	wood_type: "Порода дерева",
	moisture: "Влажность",
};
